### ISSUE TITLE
where is the model?

### ISSUE THREAD

**Issue by yumlevi** [microsoft/FILM#2]
Seems like it's not available to test atm?

Thanks.

**Comment by an1006634493** [comment]
The model is under internal review. We will release it ASAP.

**Comment by abhirupghosh** [comment]
Do we have an expected timeline for when the model will be available for public access?

**Comment by an1006634493** [comment]
The estimitated time for the general internal review is 2~4 weeks, which may be extended if there are additional assessment tasks. We will add announcements if additional assessments are assigned to our model.

**Comment by dlippold** [comment]
The model in now available on HuggingFace. That is great. But please also provide GGUF versions of the model. Files in the GGUF format are much smaller, therefore need less VRAM and there are many LLM platforms which can use GGUF files.

**Comment by an1006634493** [comment]
> The model in now available on HuggingFace. That is great. But please also provide GGUF versions of the model. Files in the GGUF format are much smaller, therefore need less VRAM and there are many LLM platforms which can use GGUF files.

Thanks for your suggestion. We provide two GGUF versions (f32 and q8_0) at [https://huggingface.co/In2Training](https://huggingface.co/In2Training).
